version: '3.7'

services:
  all-trademate-app:
    build: .
    container_name: all-trademate-app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./application.properties:/app/application.properties
      - ./allegro_token.json:/app/allegro_token.json